---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis-2
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
#    flux.weave.works/tag.chart-image: semver:4.0.14
spec:
  releaseName: redis-2
  chart:
    git: https://github.com/helm/charts.git
    path: stable/redis
    ref: master
  values:
    image:
      registry: docker.io
      repository: bitnami/redis
      tag: 4.0.14
    cluster:
      slaveCount: 1
    usePassword: false
    #    usePassword: true
    #    existingSecret: redis-secret
    sentinel:
      enabled: true
      masterSet: msis
